-- =============================================================================
-- View: gold.dim_customers
-- Description: Customer dimension with unified data from CRM and ERP.
--              Consolidates personal, geographic, and demographic information.
-- Sources:
--   - silver.crm_cust_info   → main customer data (CRM)
--   - silver.erp_cust_az12   → additional data: gender and birthdate (ERP)
--   - silver.erp_loc_a101    → location data: country (ERP)
-- Note: Gender is prioritized from CRM; if unavailable, falls back to ERP.
-- =============================================================================
CREATE VIEW gold.dim_customers AS
SELECT
    -- Surrogate key generated by customer_id order
    ROW_NUMBER() OVER (
        ORDER BY cst_id
    ) AS customer_key,
    ci.cst_id AS customer_id,        -- Internal customer ID from CRM
    ci.cst_key as customer_number,   -- Customer number (business key)
    ci.cst_firstname AS first_name,
    ci.cst_lastname AS last_name,
    la.cntry AS country,             -- Country sourced from ERP (location table)
    ci.cst_marital_status AS marital_status,
    -- Gender resolution logic: CRM takes priority over ERP
    CASE
        WHEN ci.cst_gndr IS NOT NULL
        AND ci.cst_gndr <> 'n/a' THEN ci.cst_gndr  -- Use CRM gender if valid
        ELSE COALESCE(ca.gen, 'n/a')                -- Otherwise use ERP or 'n/a'
    END AS new_gen,
    ca.bdate AS birthdate,           -- Birthdate sourced from ERP
    ci.cst_create_date AS create_date
FROM silver.crm_cust_info ci
    LEFT JOIN silver.erp_cust_az12 ca ON ci.cst_key = ca.cid  -- Enrich with ERP demographic data
    LEFT JOIN silver.erp_loc_a101 la ON ci.cst_key = la.cid   -- Enrich with ERP country data

-- =============================================================================
-- View: gold.dim_products
-- Description: Active product dimension with category information.
--              Only includes current products (no end date).
-- Sources:
--   - silver.crm_prd_info      → product data (CRM)
--   - silver.erp_px_cat_g1v2   → category, subcategory, and maintenance (ERP)
-- Note: Products with prd_end_dt IS NULL are considered active.
-- =============================================================================
CREATE VIEW gold.dim_products AS
SELECT
    -- Surrogate key generated by start date and product key order
    ROW_NUMBER() OVER (
        ORDER BY pi.prd_start_dt, pi.prd_key
    ) AS product_key,
    pi.prd_id AS product_id,         -- Internal product ID
    pi.prd_key as product_number,    -- Product number (business key)
    pi.prd_nm as product_name,
    pi.cat_id as category_id,        -- Category ID used to join with ERP
    pc.cat as category,              -- Category name sourced from ERP
    pc.subcat as subcategory,        -- Subcategory sourced from ERP
    pc.maintenance,                  -- Maintenance flag sourced from ERP
    pi.prd_cost as cost,
    pi.prd_line as product_line,
    pi.prd_start_dt as start_date
FROM silver.crm_prd_info pi
    LEFT JOIN silver.erp_px_cat_g1v2 pc ON pi.cat_id = pc.id  -- Enrich with ERP category data
WHERE
    pi.prd_end_dt IS NULL  -- Active products only (no end date)

-- =============================================================================
-- View: gold.fact_sales
-- Description: Sales fact table. Contains sales transactions linked to
--              the product and customer dimensions.
-- Sources:
--   - silver.crm_sales_details → sales transactions (CRM)
--   - gold.dim_products        → product surrogate key
--   - gold.dim_customers       → customer surrogate key
-- Granularity: One row per sales order line.
-- =============================================================================
CREATE VIEW gold.fact_sales AS
SELECT
    sls_ord_num as order_number,     -- Order number (business key)
    pr.product_key,                  -- FK → gold.dim_products
    dc.customer_key,                 -- FK → gold.dim_customers
    sls_order_dt as order_date,
    sls_ship_dt as shipping_date,
    sls_due_dt as due_date,
    sls_sales as sales_amount,       -- Total sales amount
    sls_quantity as quantity,
    sls_price price                  -- Unit price
FROM silver.crm_sales_details sd
    LEFT JOIN gold.dim_products pr ON sd.sls_prd_key = pr.product_number   -- Resolve product surrogate key
    LEFT JOIN gold.dim_customers dc ON sd.sls_cust_id = dc.customer_id     -- Resolve customer surrogate key
